'use strict';
//debugger;
var barcode = barcode || {};

barcode.C = Object.freeze({
  STATE_MENU_TO_SHOW : 0,
  STATE_MENU_SHOWN : 1,
  STATE_MENU_GOTO_DONJON : 2,
  STATE_DONJON_INPROGRESS : 3,
  STATE_DONJON_DEATH : 4,
  STATE_DONJON_QUIT : 5,
  STATE_GOTO_SCAN : 6,
  STATE_SCAN_INPROGRESS : 7,

  //direction
  DIRECTION_UP :0,
  DIRECTION_DOWN :3,
  DIRECTION_LEFT :1,
  DIRECTION_RIGHT :2,

  TILE_SIZE_PC : 32,
  TILE_SIZE_MOBILE : 64,
  TILE_SIZE_WINDOW_SIZE_LIMITE : 1200,

  ANIMATION_SPEED : 50,

//Animation type

  TYPE_ANIMATION_STATIC : 0,
  TYPE_ANIMATION_FLOATING : 1,
  TYPE_ANIMATION_TEXT_FLOATING : 1,

///ITEM TYPE
  TYPE_ITEM_NECKLACE : 0,
  TYPE_ITEM_WEAPON : 1,
  TYPE_ITEM_SHIELD : 2,
  TYPE_ITEM_ARMOR : 3,

  // type item effects
  PROPERTY_ITEM_LIFE_REGENERATION : 0,



});
